<?php
/**
 * Template Name: Search Page Templte
 */

get_header();
?>
<div class="wrap">
  <div id="primary" class="content-area">
    <main id="main" class="site-main" role="main">
      <div id="wp-vue-app">This text will be replaced the Vue App when the SPA build (generated by Webpack) is enqueued in Wordpress</div>
    </main>
  </div>
</div>
<?php get_footer(); ?>